# Generated by Django 5.2.1 on 2025-06-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='credits',
            field=models.IntegerField(default=0),
        ),
    ]
