# Generated by Django 5.2.1 on 2025-06-27 09:29

from django.utils import timezone
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_usersubscription_credits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Basic Plan', 'Pro Yearly'", max_length=100)),
                ('stripe_price_id', models.CharField(help_text='The Stripe Price ID for this plan.', max_length=255, unique=True)),
                ('plan_type', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], default='monthly', help_text='Type of subscription plan (monthly, yearly, or lifetime).', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the plan in USD.', max_digits=10)),
                ('currency', models.CharField(default='usd', help_text="Currency for the plan price, e.g., 'usd'.", max_length=10)),
                ('description', models.TextField(blank=True, help_text="A brief description of the plan's features.")),
                ('monthly_credit_allotment', models.IntegerField(default=0, help_text='Credits to assign monthly for this plan.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plan is currently offered.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='current_period_start',
            field=models.DateTimeField(default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='last_credit_refill_date',
            field=models.DateTimeField(blank=True, help_text='The last date credits were refilled for the user.', null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('canceled', 'Canceled'), ('past_due', 'Past Due'), ('unpaid', 'Unpaid'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('ended', 'Ended')], default='incomplete', help_text='Current status of the Stripe subscription.', max_length=20),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_invoice_id', models.CharField(help_text='The unique ID of the invoice in Stripe.', max_length=255, unique=True)),
                ('amount_due', models.DecimalField(decimal_places=2, help_text='The total amount due for this invoice.', max_digits=10)),
                ('currency', models.CharField(default='usd', help_text="e.g., 'usd', 'eur'", max_length=3)),
                ('status', models.CharField(help_text="Status of the invoice (e.g., 'paid', 'open', 'void').", max_length=20)),
                ('invoice_pdf', models.URLField(blank=True, help_text='URL to the invoice PDF hosted by Stripe.', max_length=500, null=True)),
                ('invoice_page', models.URLField(blank=True, help_text="URL to the invoice page on Stripe's dashboard.", max_length=500, null=True)),
                ('period_start', models.DateTimeField(help_text='The start of the billing period covered by this invoice.')),
                ('period_end', models.DateTimeField(help_text='The end of the billing period covered by this invoice.')),
                ('is_successful_payment', models.BooleanField(default=False, help_text='True if the payment for this invoice was successful.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='The active plan the user is subscribed to.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.stripeplan'),
        ),
    ]
