# Generated by Django 5.2.1 on 2025-06-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_stripeplan_usersubscription_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='user_subscription_id',
            field=models.CharField(blank=True, help_text='The ID of the subscription related to this invoice (if applicable).', max_length=100, null=True),
        ),
    ]
