# Generated by Django 5.2.1 on 2025-06-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_invoice_user_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='cancel_at_period_end_stripe',
            field=models.BooleanField(default=False, help_text='If True, the subscription is set to cancel at the end of the current billing period on Stripe.'),
        ),
    ]
